---
- name: Copy named.conf.options
  template:
    src: "named.conf.options.j2"
    dest: "{{ bind9__path }}/named.conf.options"
  notify: bind/restart

- name: "Copy named.conf.local"
  template:
    src: "templates/named.conf.local.j2"
    dest: "{{ bind9__path }}/named.conf.local"
  notify: bind/restart

- name: "Copy domain_data_file"
  template:
    src: "templates/domain_data_file.j2"
    dest: "{{ bind9__path }}/db.{{ bind9__ns_domain }}"
  notify: bind/restart

- name: Flush handlers
  meta: flush_handlers

