services:
  wg-server:
    container_name: wg-server
    image: auriema/wireguard:test
    volumes:
      - ./wireguard:/opt/wireguard
    ports:
      - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
