---
#- name: Install bind
#  apt:
#    name: bind9=1:9.18.28-1~deb12u2
#    update_cache: no
  
- name: Copy named.conf.options
  template:
    src: "named.conf.options.j2"
    dest: "{{ bind9__path }}/named.conf.options"
  notify: bind/restart

- name: "Copy named.conf.local"
  template:
    src: "templates/named.conf.local.j2"
    dest: "{{ bind9__path }}/named.conf.local"
  notify: bind/restart

- include_tasks: config.yml

- debug:
    var: bind9__ns_domain

#- name: "UFW allow Bind9"
#  ufw:
#    rule: allow
#    port: 53
#    direction: "in"
#    comment: Bind/DNS
#    to_ip: "{{ bind9__server_addr }}"
#  when: core__ufw | default(true)
