---
- name: Generate DevOps Core Tools Certificates
  hosts: localhost
  become: true
  gather_facts: no
  pre_tasks:
  - name: load variables from config.yaml
    include_vars:
      file: config.yml
  - import_role:
      name: bind9
    tags: dns_server
    vars:
      bind9__server_addr: "{{ server__internal_address }}"
      bind9__ns_domain: "{{ core__base_domain }}"
      bind9__subdomains:
        - { name: "*", addr: "{{ server__internal_address }}" }
  roles:    
  - role: wireguard/config
    tags: wg_config
  - role: wireguard/server
    tags: wg_server
