---
- name: Generate DevOps Core Tools Certificates
  hosts: localhost
  become: true
  gather_facts: no
  pre_tasks:
  - name: load variables from config.yaml
    include_vars:
      file: config.yml
  - import_role:
      name: bind9
    tags: bind9
  roles:    
  - role: wireguard/config
    tags: wg_config
  - role: wireguard/server
    tags: wg_server
