---
- name: Generate DevOps Core Tools Certificates
  hosts: localhost
  gather_facts: no
  vars:
    # server config
    server__data_path: "{{ lookup('env', 'SERVER__DATA_PATH') }}"
    server__base_domain: "{{ lookup('env', 'SERVER__BASE_DOMAIN') }}"
    server__network_prefix: "{{ lookup('env', 'SERVER__NETWORK_PREFIX') }}"
    server__internal_address: "{{ server__network_prefix }}.1"

    # WireGuard config
    wg__name: "{{ lookup('env', 'WG__NAME') }}"
    wg__server_address: "{{ lookup('env', 'WG__SERVER_ADDRESS') }}"
    wg__server_port: "{{ lookup('env', 'WG__SERVER_PORT') }}"

  pre_tasks:
  - name: load variables from config.yaml
    include_vars:
      file: "{{ lookup('env', 'SERVER__CONFIG_FILE') }}"
  roles:
  - role: bind9
    tags: bind9
  - role: wireguard
    tags: wireguard
