---
- name: "Create wireguard directory: {{ item }}"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ wg__yaml_path }}"
    - "{{ wg__conf_path }}"
    - "{{ wg__server_conf_path }}"

- include_tasks : server.yml

- include_tasks : client.yml  
  loop: "{{ wg__clients | dict2items }}"

- name: Copy server config file
  copy:
    src: "{{ wg__server_conf_file }}"
    dest: "/etc/wireguard"
  register: wg__copy_reg
