---
bind9__path: "/etc/bind"
bind9__server_addr: "{{ server__internal_address }}"
bind9__ns_domain: "{{ server__base_domain }}"
bind9__subdomains:
  - { name: "*", addr: "{{ server__internal_address }}" }
